# Generated by Django 4.2 on 2023-07-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='building_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='roomname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
