# Generated by Django 4.2 on 2023-07-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_room_name_room_building_number_room_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.course', to_field='abbreviation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
