# Generated by Django 4.2 on 2023-07-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_room_course_alter_course_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
