# Generated by Django 4.2.3 on 2023-07-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_course_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslottype', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.course', to_field='abbreviation')),
            ],
        ),
    ]
