# Generated by Django 4.2 on 2023-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_roomslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomslot',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomslot',
            name='roomslotnumber',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
