# Generated by Django 4.2 on 2023-07-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_roomslot_availability_roomslot_roomslotnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomslot',
            name='timeslot',
        ),
    ]
