# Generated by Django 4.2 on 2023-08-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_remove_roomslot_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomslot',
            name='room',
        ),
    ]
