# Generated by Django 4.2 on 2023-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_remove_roomslot_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomslot',
            name='roomslotnumber',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
