# Generated by Django 4.2 on 2023-08-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0022_remove_schedule_section_remove_schedule_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_room',
            new_name='lab_building_number',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_time',
            new_name='lab_endtime',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lecture_room',
            new_name='lab_roomname',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lecture_time',
            new_name='lab_starttime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_building_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_endtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_roomname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_starttime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
