# Generated by Django 4.2 on 2023-08-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_rename_lab_room_schedule_lab_building_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_building_number',
            new_name='laboratory_building_number',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_day',
            new_name='laboratory_day',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_endtime',
            new_name='laboratory_endtime',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_roomname',
            new_name='laboratory_roomname',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='lab_starttime',
            new_name='laboratory_starttime',
        ),
    ]
