# Generated by Django 4.2 on 2023-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0027_remove_course_unique_course_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
