# Generated by Django 4.2 on 2023-11-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursename',
        ),
        migrations.RemoveField(
            model_name='room',
            name='course',
        ),
        migrations.RemoveField(
            model_name='roomslot',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Roomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.buildinglist')),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.collegelist')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
        migrations.AddField(
            model_name='roomslot',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
    ]
