# Generated by Django 4.2 on 2023-11-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0029_buildinglist_college_collegelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
    ]
