# Generated by Django 4.2 on 2023-11-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_alter_schedule_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='coursename',
        ),
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectcode', models.CharField(blank=True, max_length=100, null=True)),
                ('subjectname', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Summer', 'Summer')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.courselist')),
            ],
        ),
    ]
