# Generated by Django 4.2 on 2023-11-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_rename_course_name_course_coursename_subjectlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_name',
            new_name='college',
        ),
    ]
