# Generated by Django 4.2 on 2023-11-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0032_rename_college_name_college_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
    ]
