# Generated by Django 4.2 on 2023-11-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0034_remove_course_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.college'),
        ),
    ]
