# Generated by Django 4.2 on 2023-11-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0035_course_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='college_name',
            new_name='college',
        ),
    ]
