# Generated by Django 4.2 on 2023-11-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0036_rename_college_name_course_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.collegelist'),
        ),
    ]
