# Generated by Django 4.2 on 2023-07-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_birthday_remove_user_gender_user_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(blank=True),
        ),
    ]
