# Generated by Django 4.2 on 2023-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(blank=True, default='First Semester', max_length=100),
        ),
    ]
