# Generated by Django 4.2 on 2023-11-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
    ]
